### ISSUE TITLE
compilation warnings for elixir 1.8.1

### ISSUE THREAD

**Issue by ayrat555** [spandex-project/spandex#97]
While running blockscout's tests I get a lot of warnings:
```
warning: the Collectable protocol is deprecated for non-empty lists. The behaviour of things like Enum.into/2 or "for" comprehensions with an :into option is incorrect when collecting into non-empty lists. If you're collecting into a non-empty keyword list, consider using Keyword.merge/2 instead. If you're collecting into a non-empty list, consider concatenating the two lists with the ++ operator.
  (elixir) lib/collectable.ex:83: Collectable.List.into/1
  (msgpax) lib/msgpax/packer.ex:151: Msgpax.Packer.List.pack/1
  (msgpax) lib/msgpax/packer.ex:152: anonymous fn/3 in Msgpax.Packer.List.pack/1
  (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
  (msgpax) lib/msgpax/packer.ex:151: Msgpax.Packer.List.pack/1
  (msgpax) lib/msgpax.ex:85: Msgpax.pack/2
  (msgpax) lib/msgpax.ex:122: Msgpax.pack!/2
  (spandex_datadog) lib/spandex_datadog/api_server.ex:192: SpandexDatadog.ApiServer.send_and_log/2
  (spandex_datadog) lib/spandex_datadog/api_server.ex:169: anonymous fn/3 in SpandexDatadog.ApiServer.handle_call/3
  (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
  (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by ayrat555** [comment]
the problem was that we used old version of `spandex_datadog`
